server:
  port: 2023
  error:
    include-message: always

---
spring:
  boot:
    admin:
      api-path: /instances
      url: http://localhost:2023
      client:
        url: http://localhost:2023
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
---
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always